import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { requireAdmin } from "@/lib/session";
import { LEVEL_LABELS, PROGRAM_STATUS_LABELS } from "@/lib/labels";

export default async function AdminProgramsPage() {
  await requireAdmin();

  const programs = await prisma.trainingProgram.findMany({
    orderBy: { updatedAt: "desc" },
    include: { _count: { select: { items: true, enrollments: true } } },
  });

  return (
    <div>
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-slate-900">
            Chương trình đào tạo
          </h1>
          <p className="mt-1 text-sm text-slate-500">
            Xây dựng thủ công hoặc tự động tạo từ kho tài liệu theo cấp độ.
          </p>
        </div>
        <Link
          href="/admin/programs/new"
          className="rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-500"
        >
          + Tạo chương trình
        </Link>
      </div>

      <div className="mt-6 overflow-hidden rounded-lg border border-slate-200 bg-white">
        <table className="w-full text-left text-sm">
          <thead className="bg-slate-50 text-xs uppercase text-slate-500">
            <tr>
              <th className="px-4 py-3">Tên chương trình</th>
              <th className="px-4 py-3">Cấp độ</th>
              <th className="px-4 py-3">Trạng thái</th>
              <th className="px-4 py-3">Số tài liệu</th>
              <th className="px-4 py-3">Người học</th>
              <th className="px-4 py-3" />
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {programs.map((p) => (
              <tr key={p.id}>
                <td className="px-4 py-3 font-medium text-slate-800">
                  {p.title}
                  {p.autoGenerated && (
                    <span className="ml-2 rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700">
                      Tự động tạo
                    </span>
                  )}
                </td>
                <td className="px-4 py-3 text-slate-600">{LEVEL_LABELS[p.level]}</td>
                <td className="px-4 py-3">
                  <span
                    className={
                      p.status === "PUBLISHED"
                        ? "rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-medium text-emerald-700"
                        : "rounded-full bg-slate-100 px-2 py-0.5 text-xs font-medium text-slate-600"
                    }
                  >
                    {PROGRAM_STATUS_LABELS[p.status]}
                  </span>
                </td>
                <td className="px-4 py-3 text-slate-600">{p._count.items}</td>
                <td className="px-4 py-3 text-slate-600">{p._count.enrollments}</td>
                <td className="px-4 py-3 text-right">
                  <Link
                    href={`/admin/programs/${p.id}/edit`}
                    className="text-indigo-600 hover:underline"
                  >
                    Quản lý
                  </Link>
                </td>
              </tr>
            ))}
            {programs.length === 0 && (
              <tr>
                <td colSpan={6} className="px-4 py-8 text-center text-slate-400">
                  Chưa có chương trình đào tạo nào.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}
